"""m8 agent avatar

Revision ID: 3d17a243bdf2
Revises: 8235f0cbfc5f
Create Date: 2026-09-16 15:23:50.932956

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3d17a243bdf2'
down_revision: str | Sequence[str] | None = '8235f0cbfc5f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('avatar_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'avatar_path')
    # ### end Alembic commands ###
