"""m7 agent skills and mcp tools

Revision ID: 8235f0cbfc5f
Revises: b874839d91c9
Create Date: 2026-09-15 00:08:54.834810

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8235f0cbfc5f'
down_revision: str | Sequence[str] | None = 'b874839d91c9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_mcp_tools',
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('mcp_server_id', sa.Uuid(), nullable=False),
    sa.Column('tool_name', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mcp_server_id'], ['mcp_servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_id', 'mcp_server_id', 'tool_name')
    )
    op.create_table('agent_skills',
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('skill_slug', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_id', 'skill_slug')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_skills')
    op.drop_table('agent_mcp_tools')
    # ### end Alembic commands ###
