"""m2 agents tools versions messages seq

Revision ID: c4637dcce147
Revises: 4616d16e6b29
Create Date: 2026-09-12 07:00:48.942043

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c4637dcce147'
down_revision: str | Sequence[str] | None = '4616d16e6b29'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tools',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('agent_tools',
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('tool_id', sa.Uuid(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_id', 'tool_id')
    )
    op.create_table('agent_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('published_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['published_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'version')
    )
    op.create_index(op.f('ix_agent_versions_agent_id'), 'agent_versions', ['agent_id'], unique=False)
    op.add_column('agents', sa.Column('emoji', sa.String(length=8), server_default='🤖', nullable=False))
    op.add_column('agents', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('agents', sa.Column('tags', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False))
    op.add_column('agents', sa.Column('system_prompt', sa.Text(), server_default='', nullable=False))
    op.add_column('agents', sa.Column('welcome_msg', sa.Text(), nullable=True))
    op.add_column('agents', sa.Column('examples', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('agents', sa.Column('current_version', sa.Integer(), server_default='1', nullable=False))
    op.add_column('agents', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_agents_owner_id'), 'agents', ['owner_id'], unique=False)
    op.add_column('messages', sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False))
    op.create_index(op.f('ix_messages_seq'), 'messages', ['seq'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_seq'), table_name='messages')
    op.drop_column('messages', 'seq')
    op.drop_index(op.f('ix_agents_owner_id'), table_name='agents')
    op.drop_column('agents', 'updated_at')
    op.drop_column('agents', 'current_version')
    op.drop_column('agents', 'examples')
    op.drop_column('agents', 'welcome_msg')
    op.drop_column('agents', 'system_prompt')
    op.drop_column('agents', 'tags')
    op.drop_column('agents', 'description')
    op.drop_column('agents', 'emoji')
    op.drop_index(op.f('ix_agent_versions_agent_id'), table_name='agent_versions')
    op.drop_table('agent_versions')
    op.drop_table('agent_tools')
    op.drop_table('tools')
    # ### end Alembic commands ###
